alias reload!='. ~/.zshrc'
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'
alias l.='ls -d .* --color=auto'
alias ls='ls -lah'
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"
alias c='clear'
alias statc='stat -c %a'
alias psw='source $HOME/source/repos.personal/jeremyj563/proxy-switcher/proxy-switcher.sh'
alias proxy_on='psw $PROXY'
alias proxy_off='psw'
